using System.ComponentModel.DataAnnotations;

public enum EquipmentEnum
{
    [Display(Name="Alchemy Kit")]
    AlchemyKit = 1,
    [Display(Name="Ball Bearings")]
    BallBearings = 2,
    [Display(Name="Bandages")]
    Bandages = 3,
    [Display(Name="Bells")]
    Bells = 4,
    [Display(Name="Book")]
    Book = 5,
    [Display(Name="Caltrops")]
    Caltrops = 6,
    [Display(Name="Chalk")]
    Chalk = 7,
    [Display(Name="Climbing Spikes")]
    ClimbingSpikes = 8,
    [Display(Name="Compass")]
    Compass = 9,
    [Display(Name="Cookware")]
    Cookware = 10,
    [Display(Name="Crowbar")]
    Crowbar = 11,
    [Display(Name="Cuffs")]
    Cuffs = 12,
    [Display(Name="Fishing Kit")]
    FishingKit = 13,
    [Display(Name="Flask")]
    Flask = 14,
    [Display(Name="Flask of Oil")]
    FlaskOfOil = 15,
    [Display(Name="Flint")]
    Flint = 16,
    [Display(Name="Goggles")]
    Goggles = 17,
    [Display(Name="Hourglass")]
    Hourglass = 18,
    [Display(Name="Iron Spikes")]
    IronSpikes = 19,
    [Display(Name="Journal, Ink, and Quill")]
    JournalInkAndQuill = 20,
    [Display(Name="Lantern")]
    Lantern = 21,
    [Display(Name="Magnifying Glass")]
    MagnifyingGlass = 22,
    [Display(Name="Mirror")]
    Mirror = 23,
    [Display(Name="Musical Instrument")]
    MusicalInstrument = 24,
    [Display(Name="Net")]
    Net = 25,
    [Display(Name="Perfume")]
    Perfume = 26,
    [Display(Name="Pickaxe")]
    Pickaxe = 27,
    [Display(Name="Rope")]
    Rope = 28,
    [Display(Name="Sewing Kit")]
    SewingKit = 29,
    [Display(Name="Shovel")]
    Shovel = 30,
    [Display(Name="Smoke Bombs")]
    SmokeBombs = 31,
    [Display(Name="Soap")]
    Soap = 32,
    [Display(Name="Spyglass")]
    Spyglass = 33,
    [Display(Name="String")]
    String = 34,
    [Display(Name="Torch")]
    Torch = 35,
    [Display(Name="Walking Stick")]
    WalkingStick = 36,
    [Display(Name="Whetstone")]
    Whetstone = 37,
    [Display(Name="Woodcutting Axe")]
    WoodcuttingAxe = 38,
    [Display(Name="Other...")]
    Other = 39,
}