using System.ComponentModel.DataAnnotations;

public enum EquipmentEnum
{
    [Display(Name="Small Cooking Pot")]
    SmallCookingPot = 1,
    [Display(Name="Cooking Utensils")]
    CookingUtensils = 2,
    [Display(Name="Flint and Tinder")]
    FlintAndTinder = 3,
    [Display(Name="Mortar and Pestle")]
    MortarAndPestle = 4,
    [Display(Name="Waterskin")]
    Waterskin = 5,
    [Display(Name="Hempen Rope")]
    HempenRope = 6,
    [Display(Name="Tinderbox")]
    Tinderbox = 7,
    [Display(Name="Compass")]
    Compass = 8,
    [Display(Name="Lantern")]
    Lantern = 9,
    [Display(Name="Crowbar")]
    Crowbar = 10,
    [Display(Name="Small Hammer")]
    SmallHammer = 11,
    [Display(Name="Magnifying Glass")]
    MagnifyingGlass = 12,
    [Display(Name="Bedroll")]
    Bedroll = 13,
    [Display(Name="Whetstone")]
    Whetstone = 14,
    [Display(Name="10x Lockpicks")]
    Lockpicks = 15,
    [Display(Name="Small Mirror")]
    SmallMirror = 16,
    [Display(Name="Chalk")]
    Chalk = 17,
    [Display(Name="10x Climbing Pitons")]
    ClimbingPitons = 18,
    [Display(Name="Journal, Ink, and Quill")]
    JournalInkAndQuill = 19,
    [Display(Name="Bag of Caltrops")]
    BagOfCaltrops = 20,
    [Display(Name="Bag of Ball Bearings")]
    BagOfBallBearings = 21,
    [Display(Name="10x Vials")]
    Vials = 22,
    [Display(Name="Ingredient Pouch")]
    IngredientPouch = 23,
    [Display(Name="Pickaxe")]
    Pickaxe = 24,
    [Display(Name="Prospector Goggles")]
    ProspectorGoggles = 25,
    [Display(Name="Gem Pouch")]
    GemPouch = 26,
    [Display(Name="Miner's Hat")]
    MinersHat = 27,
    [Display(Name="Small Anvil Block")]
    SmallAnvilBlock = 28,
    [Display(Name="Tongs")]
    Tongs = 29,
    [Display(Name="Rune Etching Pen")]
    RuneEtchingPen = 30,
    [Display(Name="Multi-Tool")]
    MultiTool = 31,
    [Display(Name="Cogs, Nuts, and Bolts")]
    CogsNutsAndBolts = 32,
    [Display(Name="2x Healing Potions")]
    HealingPotions = 33,
    [Display(Name="2x Antidotes")]
    Antidotes = 34,
    [Display(Name="2x Burn Salve")]
    BurnSalve = 35,
    [Display(Name="2x Bandages, Needle, Thread")]
    BandageNeedleThread = 36,
    [Display(Name="Skinning Knife")]
    SkinningKnife = 37,
    [Display(Name="Spare Bow String")]
    SpareBowString = 38,
    [Display(Name="Water Resistant Cloak")]
    WaterResistantCloak = 39,
    [Display(Name="2x Snares")]
    Snares = 40,
    [Display(Name="5x Flash Powder")]
    FlashPowder = 41,
    [Display(Name="Glass Cutter")]
    GlassCutter = 42,
    [Display(Name="Hourglass")]
    Hourglass = 43,
    [Display(Name="Manacles")]
    Manacles = 44,
    [Display(Name="Shovel")]
    Shovel = 45,
}