namespace TravelersTaleCharacterCreator;

public enum ProficienciesEnum
{
    Acrobatics = 1,
    Anima = 2,
    Barter = 3,
    Brawl = 4,
    Charm = 5,
    Climbing = 6,
    Constitution = 7,
    Cool = 8,
    Deduction = 9,
    Diplomacy = 10,
    Dodge = 11,
    Intimidation = 12,
    Lore = 13,
    Might = 14,
    Navigation = 15,
    Perception = 16,
    Performance = 17,
    Piloting = 18,
    Rally = 19,
    Skulduggery = 20,
    Stealth = 21,
    Streetwise = 22,
    Alchemy = 23,
    Botany = 24,
    Cooking = 25,
    Enchanting = 26,
    Fishing = 27,
    Hunting = 28,
    Mechanics = 29,
    Medicine = 30,
    Mining = 31,
    RuneCrafting = 32,
    Smithing = 33,
    Taming = 34
}