namespace TravelersTaleCharacterCreator;

public enum ProficienciesEnum
{
    Climbing = 1,
    Lifting = 2,
    Smithing = 3,
    Mining = 4,
    Skulduggery = 5,
    Stealth = 6,
    Leaping = 7,
    Lockpicking = 8,
    Mechanics = 9,
    Constitution = 10,
    Hunting = 11,
    Intimidation = 12,
    Botany = 13,
    Fishing = 14,
    Cooking = 15,
    Taming = 16,
    Navigation = 17,
    Streetwise = 18,
    Lore = 19,
    Perception = 20,
    Anima = 21,
    Deduction = 22,
    Medicine = 23,
    Alchemy = 24,
    Barter = 25,
    Charm = 26,
    Rally = 27,
    Cool = 28,
    Diplomacy = 29,
    Performance = 30,
    Enchanting = 31,
    RuneCrafting = 32,
}